version: '3'

services:
  mongo: # database
    image: mongo:latest # pull the mongo image from docker hub
    logging: 
      driver: none # disable logging
    ports:
      - '27017:27017'
  
  rabbitmq: # rabbitmq
    image: rabbitmq:latest # pull the rabbitmq image from  dockerhub
    logging: 
      driver: none # disable logging
    ports:
      - '5672:5672'